# Site settings
title: gmbjjwnc
email: gmbjjwnc68@yahoo.com
year: 2025
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/front/" # the subpath of your site, e.g. /blog/
url: "www.gmbjjwnc.com" # the base hostname & protocol for your site

instagram_username: gmbjjwnc
facebook_username: gmbjjwnc68

# Build settings
markdown: kramdown
